import os
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForSeq2SeqLM

# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# 1. Classification Model Directory
# This is the directory where model_2.py saves the fine-tuned DistilBERT model.
CLASSIFICATION_MODEL_DIR = "./legal_petition_model" 
if not os.path.exists(CLASSIFICATION_MODEL_DIR):
    CLASSIFICATION_MODEL_DIR = "./legalverse_task1_model" # fallback

# 2. Generative LLM Strategy
# ==========================================
# We use a powerful modern Small Language Model (SLM) running 100% locally.
# Qwen2.5-1.5B-Instruct provides excellent reasoning and instruction following without needing an API.
GENERATIVE_MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"


def load_classification_model(model_dir):
    """Loads the DistilBERT / classifier model."""
    print(f"Loading Classification Model from {model_dir}...")
    tokenizer = AutoTokenizer.from_pretrained(model_dir)
    model = AutoModelForSequenceClassification.from_pretrained(model_dir)
    model.to(DEVICE)
    model.eval()
    return tokenizer, model

def load_generative_model(model_name):
    """Loads the local Qwen Instruct model for generation."""
    from transformers import AutoModelForCausalLM
    print(f"Loading Local Generative LLM ({model_name})...")
    print("This will download ~3GB of weights on the first run.")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    # Load in lower precision if possible to save RAM, but defaults to full/fp16 based on device
    model = AutoModelForCausalLM.from_pretrained(
        model_name, 
        torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
        low_cpu_mem_usage=True
    )
    model.to(DEVICE)
    model.eval()
    return tokenizer, model

def predict_admission(text, clf_tokenizer, clf_model):
    """Predicts Admitted (1) or Dismissed (0) using the classification model."""
    inputs = clf_tokenizer(text, return_tensors="pt", truncation=True, max_length=512, padding=True).to(DEVICE)
    with torch.no_grad():
        logits = clf_model(**inputs).logits
        probs = torch.softmax(logits, dim=-1).squeeze()
        
    pred_class = probs.argmax().item()
    confidence = float(probs[pred_class])
    
    label = "Admitted" if pred_class == 1 else "Dismissed"
    return label, confidence

def generate_explanation_and_suggestions(text, prediction, generator):
    """
    Constructs a prompt with the petition text and its predicted outcome,
    then uses the Qwen LLM to write reasoning and suggestions using a Chat structure.
    """
    if len(text) > 2000:
        text = text[:2000] + "... [truncated]"

    system_prompt = "You are an expert legal assistant. You provide concise, professional legal reasoning and structure your outputs exactly as requested."
    user_prompt = f"""
Analyze the following legal petition that was {prediction}.
Write a short paragraph explaining the concise legal reasoning for why it was {prediction} based on the text. 
Then, you MUST provide a numbered list of exactly 3 actionable suggested improvements for the petition.

Petition Text:
"{text}"

You MUST format your output EXACTLY like this:
The writ petition was {prediction.lower()} primarily because [insert concise reasoning here based on the text].

Suggested Improvements:
1. [Improvement 1]
2. [Improvement 2]
3. [Improvement 3]
"""

    tokenizer, model = generator
    
    # Format messages for the Instruction-tuned model
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    
    text_input = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    
    model_inputs = tokenizer([text_input], return_tensors="pt").to(DEVICE)
    
    print("Generating reasoning and suggestions (this may take a moment)...")
    
    with torch.no_grad():
        generated_ids = model.generate(
            **model_inputs,
            max_new_tokens=400, # Increased to ensure it finishes the list
            temperature=0.2, # Lower temp for strict formatting
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
        
    # We only want to decode the *new* tokens generated by the model, not the prompt.
    prompt_length = model_inputs.input_ids.shape[1]
    generated_tokens = generated_ids[0][prompt_length:]
    
    final_output = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
        
    return final_output

def analyze_petition(petition_text, clf_tokenizer, clf_model, gen_model):
    """Full pipeline: Classify -> Draft Explanation -> Print"""
    print("\n" + "="*50)
    print("ANALYZING PETITION...")
    print("="*50)
    
    # Step 1: Predict
    prediction_label, confidence = predict_admission(petition_text, clf_tokenizer, clf_model)
    print(f"Prediction : {prediction_label.upper()}")
    print(f"Confidence : {confidence*100:.2f}%\n")
    
    # Step 2: Generate Explanation
    try:
        print("Generating reasoning and suggestions (this may take a moment)...")
        explanation = generate_explanation_and_suggestions(petition_text, prediction_label, gen_model)
        
        print("Generated Output:")
        print("-" * 50)
        print(explanation)
        print("-" * 50)
        
    except Exception as e:
        print(f"Error during generation: {e}")
        

if __name__ == "__main__":
    import sys
    import argparse
    
    parser = argparse.ArgumentParser(description="Analyze a legal petition and generate reasoning/suggestions.")
    parser.add_argument("petition_file", help="Path to a text file containing the legal petition.")
    args = parser.parse_args()

    # Verify classifier exists
    if not os.path.exists(CLASSIFICATION_MODEL_DIR):
        print(f"Error: Could not find classification model at {CLASSIFICATION_MODEL_DIR}")
        print("Please train your model using model_2.py first or update the CLASSIFICATION_MODEL_DIR variable.")
        sys.exit(1)
        
    # Read the petition file
    if not os.path.exists(args.petition_file):
        print(f"Error: Could not find petition file at {args.petition_file}")
        sys.exit(1)
        
    with open(args.petition_file, "r", encoding="utf-8") as f:
        petition_text = f.read().strip()
        
    if not petition_text:
        print("Error: The provided petition file is empty.")
        sys.exit(1)
        
    # Load Models
    clf_tokenizer, clf_model = load_classification_model(CLASSIFICATION_MODEL_DIR)
    gen_model = load_generative_model(GENERATIVE_MODEL_NAME)
    
    # Run Analysis
    analyze_petition(petition_text, clf_tokenizer, clf_model, gen_model)
    
    print("\nNow you can integrate `analyze_petition` function into your application.")
